name: Deploy Canary

on:
  push:
    branches:
      - next

# Allow one concurrent deployment
concurrency:
  group: "canary"
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Docs
        run: pnpm run build:dev

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.S3_TEST_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_TEST_SECRET_KEY }}
          aws-region: us-west-1
          
      - name: Deploy to S3
        run: aws s3 sync ./dist s3://ones-com-developer-static-test

      - name: send notification
        run: >
          curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=20dc3e3c-dfa4-4d10-8900-292810e5b046' -H 'Content-Type: application/json' -d '{
            "msgtype": "template_card",
            "template_card": {
              "card_type": "text_notice",
              "card_action": {
                "type": 1,
                "url": "https://developer.dev-ones.site/"
              },
              "source": {
                "desc": "å¼€æ”¾å¹³å°å†…éƒ¨æ–‡æ¡£"
              },
              "main_title": {
                "title": "ğŸ¦‹ å‘å¸ƒæˆåŠŸ"
              },
              "horizontal_content_list": [
                {
                  "keyname": "å‘å¸ƒäºº",
                  "value": "${{ github.actor }}"
                }
              ],
              "jump_list": [
                {
                  "type": 1,
                  "url": "https://developer.ones.com/",
                  "title": "è®¿é—®æ­£å¼æ–‡æ¡£"
                }
              ]
            }
          }'